use group05;
start transaction;
begin;
-- Gender
-- ------------------------------------------------
insert into gender (gender_name) values  ('Male');
insert into gender (gender_name) values  ('Female');
insert into gender (gender_name) values  ('Trans Gender (M/F');
insert into gender (gender_name) values  ('Trans Gender (F/M');



-- City
-- ------------------------------------------------
insert into city (City,County,geo_x , geo_y) values  ('Belfast','Antrim',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Armagh','Armagh',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Carlow','Carlow',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Cavan','Cavan',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Ennis','Clare',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Cork','Cork',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Derry','Derry',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Donegal','Donegal',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Newry','Down',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Dublin','Dublin',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Enniskillen','Fermanagh',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Galway','Galway',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Killarney','Kerry',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Newbridge','Kildare',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Killarney','Kilkenny',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Portlaoise','Laois',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Carrick on Shannon','Leitrim',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Limerick','Limerick',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Longford','Longford',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Dundalk','Louth',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Westport','Mayo',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Drogheda','Meath',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Monaghan','Monaghan',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Tullamore','Offaly',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Roscommon','Roscommon',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Sligo','Sligo',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Tipperary','Tipperary',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Omagh','Tyrone',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Waterford','Waterford',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Athlone','Westmeath',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Waterford','Wexford',0,0);
insert into city (City,County,geo_x , geo_y) values  ('Arklow','Wicklow',0,0);





-- relationship_type
-- ------------------------------------------------
insert into relationship_type (relationship_type) values  ('love');
insert into relationship_type (relationship_type) values  ('casual');
insert into relationship_type (relationship_type) values  ('friendship');
insert into relationship_type (relationship_type) values  ('relationship');



-- interests
-- ------------------------------------------------
insert into interests (description) values  ('Music');
insert into interests (description) values  ('Sport');
insert into interests (description) values  ('Travelling');
insert into interests (description) values  ('Sailing');
insert into interests (description) values  ('Food');
insert into interests (description) values  ('Work');
insert into interests (description) values  ('Family');
insert into interests (description) values  ('Cooking');
insert into interests (description) values  ('Gym');



-- black_list_words
-- ------------------------------------------------
insert into black_list_word (word) values  ('a55');
insert into black_list_word (word) values  ('a55hole');
insert into black_list_word (word) values  ('aeolus');
insert into black_list_word (word) values  ('ahole');
insert into black_list_word (word) values  ('anal');
insert into black_list_word (word) values  ('analprobe');
insert into black_list_word (word) values  ('anilingus');
insert into black_list_word (word) values  ('anus');
insert into black_list_word (word) values  ('areola');
insert into black_list_word (word) values  ('areole');
insert into black_list_word (word) values  ('arian');
insert into black_list_word (word) values  ('aryan');
insert into black_list_word (word) values  ('ass');
insert into black_list_word (word) values  ('assbang');
insert into black_list_word (word) values  ('assbanged');
insert into black_list_word (word) values  ('assbangs');
insert into black_list_word (word) values  ('asses');
insert into black_list_word (word) values  ('assfuck');
insert into black_list_word (word) values  ('assfucker');
insert into black_list_word (word) values  ('assh0le');
insert into black_list_word (word) values  ('asshat');
insert into black_list_word (word) values  ('assho1e');
insert into black_list_word (word) values  ('ass hole');
insert into black_list_word (word) values  ('assholes');
insert into black_list_word (word) values  ('assmaster');
insert into black_list_word (word) values  ('assmunch');
insert into black_list_word (word) values  ('asswipe');
insert into black_list_word (word) values  ('asswipes');
insert into black_list_word (word) values  ('azazel');
insert into black_list_word (word) values  ('azz');
insert into black_list_word (word) values  ('b1tch');
insert into black_list_word (word) values  ('babe');
insert into black_list_word (word) values  ('babes');
insert into black_list_word (word) values  ('ballsack');
insert into black_list_word (word) values  ('bang');
insert into black_list_word (word) values  ('banger');
insert into black_list_word (word) values  ('barf');
insert into black_list_word (word) values  ('bastard');
insert into black_list_word (word) values  ('bastards');
insert into black_list_word (word) values  ('bawdy');
insert into black_list_word (word) values  ('beaner');
insert into black_list_word (word) values  ('beardedclam');
insert into black_list_word (word) values  ('beastiality');
insert into black_list_word (word) values  ('beatch');
insert into black_list_word (word) values  ('beater');
insert into black_list_word (word) values  ('beaver');
insert into black_list_word (word) values  ('beer');
insert into black_list_word (word) values  ('beeyotch');
insert into black_list_word (word) values  ('beotch');
insert into black_list_word (word) values  ('biatch');
insert into black_list_word (word) values  ('bigtits');
insert into black_list_word (word) values  ('big tits');
insert into black_list_word (word) values  ('bimbo');
insert into black_list_word (word) values  ('bitch');
insert into black_list_word (word) values  ('bitched');
insert into black_list_word (word) values  ('bitches');
insert into black_list_word (word) values  ('bitchy');
insert into black_list_word (word) values  ('blow job');
insert into black_list_word (word) values  ('blow');
insert into black_list_word (word) values  ('blowjob');
insert into black_list_word (word) values  ('blowjobs');
insert into black_list_word (word) values  ('bod');
insert into black_list_word (word) values  ('bodily');
insert into black_list_word (word) values  ('boink');
insert into black_list_word (word) values  ('bollock');
insert into black_list_word (word) values  ('bollocks');
insert into black_list_word (word) values  ('bollok');
insert into black_list_word (word) values  ('bone');
insert into black_list_word (word) values  ('boned');
insert into black_list_word (word) values  ('boner');
insert into black_list_word (word) values  ('boners');
insert into black_list_word (word) values  ('bong');
insert into black_list_word (word) values  ('boob');
insert into black_list_word (word) values  ('boobies');
insert into black_list_word (word) values  ('boobs');
insert into black_list_word (word) values  ('booby');
insert into black_list_word (word) values  ('booger');
insert into black_list_word (word) values  ('bookie');
insert into black_list_word (word) values  ('bootee');
insert into black_list_word (word) values  ('bootie');
insert into black_list_word (word) values  ('booty');
insert into black_list_word (word) values  ('booze');
insert into black_list_word (word) values  ('boozer');
insert into black_list_word (word) values  ('boozy');
insert into black_list_word (word) values  ('bosom');
insert into black_list_word (word) values  ('bosomy');
insert into black_list_word (word) values  ('bowel');
insert into black_list_word (word) values  ('bowels');
insert into black_list_word (word) values  ('bra');
insert into black_list_word (word) values  ('brassiere');
insert into black_list_word (word) values  ('breast');
insert into black_list_word (word) values  ('breasts');
insert into black_list_word (word) values  ('bugger');
insert into black_list_word (word) values  ('bukkake');
insert into black_list_word (word) values  ('bullshit');
insert into black_list_word (word) values  ('bull shit');
insert into black_list_word (word) values  ('bullshits');
insert into black_list_word (word) values  ('bullshitted');
insert into black_list_word (word) values  ('bullturds');
insert into black_list_word (word) values  ('bung');
insert into black_list_word (word) values  ('busty');
insert into black_list_word (word) values  ('butt');
insert into black_list_word (word) values  ('butt fuck');
insert into black_list_word (word) values  ('buttfuck');
insert into black_list_word (word) values  ('buttfucker');
insert into black_list_word (word) values  ('buttfucker');
insert into black_list_word (word) values  ('buttplug');
insert into black_list_word (word) values  ('c.0.c.k');
insert into black_list_word (word) values  ('c.o.c.k.');
insert into black_list_word (word) values  ('c.u.n.t');
insert into black_list_word (word) values  ('c0ck');
insert into black_list_word (word) values  ('c-0-c-k');
insert into black_list_word (word) values  ('caca');
insert into black_list_word (word) values  ('cahone');
insert into black_list_word (word) values  ('cameltoe');
insert into black_list_word (word) values  ('carpetmuncher');
insert into black_list_word (word) values  ('cawk');
insert into black_list_word (word) values  ('cervix');
insert into black_list_word (word) values  ('chinc');
insert into black_list_word (word) values  ('chincs');
insert into black_list_word (word) values  ('chink');
insert into black_list_word (word) values  ('chink');
insert into black_list_word (word) values  ('chode');
insert into black_list_word (word) values  ('chodes');
insert into black_list_word (word) values  ('cl1t');
insert into black_list_word (word) values  ('climax');
insert into black_list_word (word) values  ('clit');
insert into black_list_word (word) values  ('clitoris');
insert into black_list_word (word) values  ('clitorus');
insert into black_list_word (word) values  ('clits');
insert into black_list_word (word) values  ('clitty');
insert into black_list_word (word) values  ('cocain');
insert into black_list_word (word) values  ('cocaine');
insert into black_list_word (word) values  ('cock');
insert into black_list_word (word) values  ('c-o-c-k');
insert into black_list_word (word) values  ('cockblock');
insert into black_list_word (word) values  ('cockholster');
insert into black_list_word (word) values  ('cockknocker');
insert into black_list_word (word) values  ('cocks');
insert into black_list_word (word) values  ('cocksmoker');
insert into black_list_word (word) values  ('cocksucker');
insert into black_list_word (word) values  ('cock sucker');
insert into black_list_word (word) values  ('coital');
insert into black_list_word (word) values  ('commie');
insert into black_list_word (word) values  ('condom');
insert into black_list_word (word) values  ('coon');
insert into black_list_word (word) values  ('coons');
insert into black_list_word (word) values  ('corksucker');
insert into black_list_word (word) values  ('crabs');
insert into black_list_word (word) values  ('crack');
insert into black_list_word (word) values  ('cracker');
insert into black_list_word (word) values  ('crackwhore');
insert into black_list_word (word) values  ('crap');
insert into black_list_word (word) values  ('crappy');
insert into black_list_word (word) values  ('cum');
insert into black_list_word (word) values  ('cummin');
insert into black_list_word (word) values  ('cumming');
insert into black_list_word (word) values  ('cumshot');
insert into black_list_word (word) values  ('cumshots');
insert into black_list_word (word) values  ('cumslut');
insert into black_list_word (word) values  ('cumstain');
insert into black_list_word (word) values  ('cunilingus');
insert into black_list_word (word) values  ('cunnilingus');
insert into black_list_word (word) values  ('cunny');
insert into black_list_word (word) values  ('cunt');
insert into black_list_word (word) values  ('cunt');
insert into black_list_word (word) values  ('c-u-n-t');
insert into black_list_word (word) values  ('cuntface');
insert into black_list_word (word) values  ('cunthunter');
insert into black_list_word (word) values  ('cuntlick');
insert into black_list_word (word) values  ('cuntlicker');
insert into black_list_word (word) values  ('cunts');
insert into black_list_word (word) values  ('d0ng');
insert into black_list_word (word) values  ('d0uch3');
insert into black_list_word (word) values  ('d0uche');
insert into black_list_word (word) values  ('d1ck');
insert into black_list_word (word) values  ('d1ld0');
insert into black_list_word (word) values  ('d1ldo');
insert into black_list_word (word) values  ('dago');
insert into black_list_word (word) values  ('dagos');
insert into black_list_word (word) values  ('dammit');
insert into black_list_word (word) values  ('damn');
insert into black_list_word (word) values  ('damned');
insert into black_list_word (word) values  ('damnit');
insert into black_list_word (word) values  ('dawgie-style');
insert into black_list_word (word) values  ('dick');
insert into black_list_word (word) values  ('dickbag');
insert into black_list_word (word) values  ('dickdipper');
insert into black_list_word (word) values  ('dickface');
insert into black_list_word (word) values  ('dickflipper');
insert into black_list_word (word) values  ('dickhead');
insert into black_list_word (word) values  ('dickheads');
insert into black_list_word (word) values  ('dickish');
insert into black_list_word (word) values  ('dick-ish');
insert into black_list_word (word) values  ('dickripper');
insert into black_list_word (word) values  ('dicksipper');
insert into black_list_word (word) values  ('dickweed');
insert into black_list_word (word) values  ('dickwhipper');
insert into black_list_word (word) values  ('dickzipper');
insert into black_list_word (word) values  ('diddle');
insert into black_list_word (word) values  ('dike');
insert into black_list_word (word) values  ('dildo');
insert into black_list_word (word) values  ('dildos');
insert into black_list_word (word) values  ('diligaf');
insert into black_list_word (word) values  ('dillweed');
insert into black_list_word (word) values  ('dimwit');
insert into black_list_word (word) values  ('dingle');
insert into black_list_word (word) values  ('dipship');
insert into black_list_word (word) values  ('doggie-style');
insert into black_list_word (word) values  ('doggy-style');
insert into black_list_word (word) values  ('dong');
insert into black_list_word (word) values  ('doofus');
insert into black_list_word (word) values  ('doosh');
insert into black_list_word (word) values  ('dopey');
insert into black_list_word (word) values  ('douch3');
insert into black_list_word (word) values  ('douche');
insert into black_list_word (word) values  ('douchebag');
insert into black_list_word (word) values  ('douchebags');
insert into black_list_word (word) values  ('douchey');
insert into black_list_word (word) values  ('drunk');
insert into black_list_word (word) values  ('dumass');
insert into black_list_word (word) values  ('dumbass');
insert into black_list_word (word) values  ('dumbasses');
insert into black_list_word (word) values  ('dummy');
insert into black_list_word (word) values  ('dyke');
insert into black_list_word (word) values  ('dykes');
insert into black_list_word (word) values  ('ejaculate');
insert into black_list_word (word) values  ('enlargement');
insert into black_list_word (word) values  ('erect');
insert into black_list_word (word) values  ('erection');
insert into black_list_word (word) values  ('erotic');
insert into black_list_word (word) values  ('essohbee');
insert into black_list_word (word) values  ('extacy');
insert into black_list_word (word) values  ('extasy');
insert into black_list_word (word) values  ('f.u.c.k');
insert into black_list_word (word) values  ('fack');
insert into black_list_word (word) values  ('fag');
insert into black_list_word (word) values  ('fagg');
insert into black_list_word (word) values  ('fagged');
insert into black_list_word (word) values  ('faggit');
insert into black_list_word (word) values  ('faggot');
insert into black_list_word (word) values  ('fagot');
insert into black_list_word (word) values  ('fags');
insert into black_list_word (word) values  ('faig');
insert into black_list_word (word) values  ('faigt');
insert into black_list_word (word) values  ('fannybandit');
insert into black_list_word (word) values  ('fart');
insert into black_list_word (word) values  ('fartknocker');
insert into black_list_word (word) values  ('fat');
insert into black_list_word (word) values  ('felch');
insert into black_list_word (word) values  ('felcher');
insert into black_list_word (word) values  ('felching');
insert into black_list_word (word) values  ('fellate');
insert into black_list_word (word) values  ('fellatio');
insert into black_list_word (word) values  ('feltch');
insert into black_list_word (word) values  ('feltcher');
insert into black_list_word (word) values  ('fisted');
insert into black_list_word (word) values  ('fisting');
insert into black_list_word (word) values  ('fisty');
insert into black_list_word (word) values  ('floozy');
insert into black_list_word (word) values  ('foad');
insert into black_list_word (word) values  ('fondle');
insert into black_list_word (word) values  ('foobar');
insert into black_list_word (word) values  ('foreskin');
insert into black_list_word (word) values  ('freex');
insert into black_list_word (word) values  ('frigg');
insert into black_list_word (word) values  ('frigga');
insert into black_list_word (word) values  ('fubar');
insert into black_list_word (word) values  ('fuck');
insert into black_list_word (word) values  ('f-u-c-k');
insert into black_list_word (word) values  ('fuckass');
insert into black_list_word (word) values  ('fucked');
insert into black_list_word (word) values  ('fucked');
insert into black_list_word (word) values  ('fucker');
insert into black_list_word (word) values  ('fuckface');
insert into black_list_word (word) values  ('fuckin');
insert into black_list_word (word) values  ('fucking');
insert into black_list_word (word) values  ('fucknugget');
insert into black_list_word (word) values  ('fucknut');
insert into black_list_word (word) values  ('fuckoff');
insert into black_list_word (word) values  ('fucks');
insert into black_list_word (word) values  ('fucktard');
insert into black_list_word (word) values  ('fuck-tard');
insert into black_list_word (word) values  ('fuckup');
insert into black_list_word (word) values  ('fuckwad');
insert into black_list_word (word) values  ('fuckwit');
insert into black_list_word (word) values  ('fudgepacker');
insert into black_list_word (word) values  ('fuk');
insert into black_list_word (word) values  ('fvck');
insert into black_list_word (word) values  ('fxck');
insert into black_list_word (word) values  ('gae');
insert into black_list_word (word) values  ('gai');
insert into black_list_word (word) values  ('ganja');
insert into black_list_word (word) values  ('gay');
insert into black_list_word (word) values  ('gays');
insert into black_list_word (word) values  ('gey');
insert into black_list_word (word) values  ('gfy');
insert into black_list_word (word) values  ('ghay');
insert into black_list_word (word) values  ('ghey');
insert into black_list_word (word) values  ('gigolo');
insert into black_list_word (word) values  ('glans');
insert into black_list_word (word) values  ('goatse');
insert into black_list_word (word) values  ('godamn');
insert into black_list_word (word) values  ('godamnit');
insert into black_list_word (word) values  ('goddam');
insert into black_list_word (word) values  ('goddammit');
insert into black_list_word (word) values  ('goddamn');
insert into black_list_word (word) values  ('goldenshower');
insert into black_list_word (word) values  ('gonad');
insert into black_list_word (word) values  ('gonads');
insert into black_list_word (word) values  ('gook');
insert into black_list_word (word) values  ('gooks');
insert into black_list_word (word) values  ('gringo');
insert into black_list_word (word) values  ('gspot');
insert into black_list_word (word) values  ('g-spot');
insert into black_list_word (word) values  ('gtfo');
insert into black_list_word (word) values  ('guido');
insert into black_list_word (word) values  ('h0m0');
insert into black_list_word (word) values  ('h0mo');
insert into black_list_word (word) values  ('handjob');
insert into black_list_word (word) values  ('hard on');
insert into black_list_word (word) values  ('he11');
insert into black_list_word (word) values  ('hebe');
insert into black_list_word (word) values  ('heeb');
insert into black_list_word (word) values  ('hell');
insert into black_list_word (word) values  ('hemp');
insert into black_list_word (word) values  ('heroin');
insert into black_list_word (word) values  ('herp');
insert into black_list_word (word) values  ('herpes');
insert into black_list_word (word) values  ('herpy');
insert into black_list_word (word) values  ('hitler');
insert into black_list_word (word) values  ('hiv');
insert into black_list_word (word) values  ('hobag');
insert into black_list_word (word) values  ('hom0');
insert into black_list_word (word) values  ('homey');
insert into black_list_word (word) values  ('homo');
insert into black_list_word (word) values  ('homoey');
insert into black_list_word (word) values  ('honky');
insert into black_list_word (word) values  ('hooch');
insert into black_list_word (word) values  ('hookah');
insert into black_list_word (word) values  ('hooker');
insert into black_list_word (word) values  ('hoor');
insert into black_list_word (word) values  ('hootch');
insert into black_list_word (word) values  ('hooter');
insert into black_list_word (word) values  ('hooters');
insert into black_list_word (word) values  ('horny');
insert into black_list_word (word) values  ('hump');
insert into black_list_word (word) values  ('humped');
insert into black_list_word (word) values  ('humping');
insert into black_list_word (word) values  ('hussy');
insert into black_list_word (word) values  ('hymen');
insert into black_list_word (word) values  ('inbred');
insert into black_list_word (word) values  ('incest');
insert into black_list_word (word) values  ('injun');
insert into black_list_word (word) values  ('j3rk0ff');
insert into black_list_word (word) values  ('jackass');
insert into black_list_word (word) values  ('jackhole');
insert into black_list_word (word) values  ('jackoff');
insert into black_list_word (word) values  ('jap');
insert into black_list_word (word) values  ('japs');
insert into black_list_word (word) values  ('jerk');
insert into black_list_word (word) values  ('jerk0ff');
insert into black_list_word (word) values  ('jerked');
insert into black_list_word (word) values  ('jerkoff');
insert into black_list_word (word) values  ('jism');
insert into black_list_word (word) values  ('jiz');
insert into black_list_word (word) values  ('jizm');
insert into black_list_word (word) values  ('jizz');
insert into black_list_word (word) values  ('jizzed');
insert into black_list_word (word) values  ('junkie');
insert into black_list_word (word) values  ('junky');
insert into black_list_word (word) values  ('kike');
insert into black_list_word (word) values  ('kikes');
insert into black_list_word (word) values  ('kill');
insert into black_list_word (word) values  ('kinky');
insert into black_list_word (word) values  ('kkk');
insert into black_list_word (word) values  ('klan');
insert into black_list_word (word) values  ('knobend');
insert into black_list_word (word) values  ('kooch');
insert into black_list_word (word) values  ('kooches');
insert into black_list_word (word) values  ('kootch');
insert into black_list_word (word) values  ('kraut');
insert into black_list_word (word) values  ('kyke');
insert into black_list_word (word) values  ('labia');
insert into black_list_word (word) values  ('lech');
insert into black_list_word (word) values  ('leper');
insert into black_list_word (word) values  ('lesbians');
insert into black_list_word (word) values  ('lesbo');
insert into black_list_word (word) values  ('lesbos');
insert into black_list_word (word) values  ('lez');
insert into black_list_word (word) values  ('lezbian');
insert into black_list_word (word) values  ('lezbians');
insert into black_list_word (word) values  ('lezbo');
insert into black_list_word (word) values  ('lezbos');
insert into black_list_word (word) values  ('lezzie');
insert into black_list_word (word) values  ('lezzies');
insert into black_list_word (word) values  ('lezzy');
insert into black_list_word (word) values  ('lmao');
insert into black_list_word (word) values  ('lmfao');
insert into black_list_word (word) values  ('loin');
insert into black_list_word (word) values  ('loins');
insert into black_list_word (word) values  ('lube');
insert into black_list_word (word) values  ('lusty');
insert into black_list_word (word) values  ('mams');
insert into black_list_word (word) values  ('massa');
insert into black_list_word (word) values  ('masterbate');
insert into black_list_word (word) values  ('masterbating');
insert into black_list_word (word) values  ('masterbation');
insert into black_list_word (word) values  ('masturbate');
insert into black_list_word (word) values  ('masturbating');
insert into black_list_word (word) values  ('masturbation');
insert into black_list_word (word) values  ('maxi');
insert into black_list_word (word) values  ('menses');
insert into black_list_word (word) values  ('menstruate');
insert into black_list_word (word) values  ('menstruation');
insert into black_list_word (word) values  ('meth');
insert into black_list_word (word) values  ('m-fucking');
insert into black_list_word (word) values  ('mofo');
insert into black_list_word (word) values  ('molest');
insert into black_list_word (word) values  ('moolie');
insert into black_list_word (word) values  ('moron');
insert into black_list_word (word) values  ('motherfucka');
insert into black_list_word (word) values  ('motherfucker');
insert into black_list_word (word) values  ('motherfucking');
insert into black_list_word (word) values  ('mtherfucker');
insert into black_list_word (word) values  ('mthrfucker');
insert into black_list_word (word) values  ('mthrfucking');
insert into black_list_word (word) values  ('muff');
insert into black_list_word (word) values  ('muffdiver');
insert into black_list_word (word) values  ('murder');
insert into black_list_word (word) values  ('muthafuckaz');
insert into black_list_word (word) values  ('muthafucker');
insert into black_list_word (word) values  ('mutherfucker');
insert into black_list_word (word) values  ('mutherfucking');
insert into black_list_word (word) values  ('muthrfucking');
insert into black_list_word (word) values  ('nad');
insert into black_list_word (word) values  ('nads');
insert into black_list_word (word) values  ('naked');
insert into black_list_word (word) values  ('napalm');
insert into black_list_word (word) values  ('nappy');
insert into black_list_word (word) values  ('nazi');
insert into black_list_word (word) values  ('nazism');
insert into black_list_word (word) values  ('negro');
insert into black_list_word (word) values  ('nigga');
insert into black_list_word (word) values  ('niggah');
insert into black_list_word (word) values  ('niggas');
insert into black_list_word (word) values  ('niggaz');
insert into black_list_word (word) values  ('nigger');
insert into black_list_word (word) values  ('nigger');
insert into black_list_word (word) values  ('niggers');
insert into black_list_word (word) values  ('niggle');
insert into black_list_word (word) values  ('niglet');
insert into black_list_word (word) values  ('nimrod');
insert into black_list_word (word) values  ('ninny');
insert into black_list_word (word) values  ('nipple');
insert into black_list_word (word) values  ('nooky');
insert into black_list_word (word) values  ('nympho');
insert into black_list_word (word) values  ('opiate');
insert into black_list_word (word) values  ('opium');
insert into black_list_word (word) values  ('oral');
insert into black_list_word (word) values  ('orally');
insert into black_list_word (word) values  ('organ');
insert into black_list_word (word) values  ('orgasm');
insert into black_list_word (word) values  ('orgasmic');
insert into black_list_word (word) values  ('orgies');
insert into black_list_word (word) values  ('orgy');
insert into black_list_word (word) values  ('ovary');
insert into black_list_word (word) values  ('ovum');
insert into black_list_word (word) values  ('ovums');
insert into black_list_word (word) values  ('p.u.s.s.y.');
insert into black_list_word (word) values  ('paddy');
insert into black_list_word (word) values  ('paki');
insert into black_list_word (word) values  ('pantie');
insert into black_list_word (word) values  ('panties');
insert into black_list_word (word) values  ('panty');
insert into black_list_word (word) values  ('pastie');
insert into black_list_word (word) values  ('pasty');
insert into black_list_word (word) values  ('pcp');
insert into black_list_word (word) values  ('pecker');
insert into black_list_word (word) values  ('pedo');
insert into black_list_word (word) values  ('pedophile');
insert into black_list_word (word) values  ('pedophilia');
insert into black_list_word (word) values  ('pedophiliac');
insert into black_list_word (word) values  ('pee');
insert into black_list_word (word) values  ('peepee');
insert into black_list_word (word) values  ('penetrate');
insert into black_list_word (word) values  ('penetration');
insert into black_list_word (word) values  ('penial');
insert into black_list_word (word) values  ('penile');
insert into black_list_word (word) values  ('penis');
insert into black_list_word (word) values  ('perversion');
insert into black_list_word (word) values  ('peyote');
insert into black_list_word (word) values  ('phalli');
insert into black_list_word (word) values  ('phallic');
insert into black_list_word (word) values  ('phuck');
insert into black_list_word (word) values  ('pillowbiter');
insert into black_list_word (word) values  ('pimp');
insert into black_list_word (word) values  ('pinko');
insert into black_list_word (word) values  ('piss');
insert into black_list_word (word) values  ('pissed');
insert into black_list_word (word) values  ('pissoff');
insert into black_list_word (word) values  ('piss-off');
insert into black_list_word (word) values  ('pms');
insert into black_list_word (word) values  ('polack');
insert into black_list_word (word) values  ('pollock');
insert into black_list_word (word) values  ('poon');
insert into black_list_word (word) values  ('poontang');
insert into black_list_word (word) values  ('porn');
insert into black_list_word (word) values  ('porno');
insert into black_list_word (word) values  ('pornography');
insert into black_list_word (word) values  ('pot');
insert into black_list_word (word) values  ('potty');
insert into black_list_word (word) values  ('prick');
insert into black_list_word (word) values  ('prig');
insert into black_list_word (word) values  ('prostitute');
insert into black_list_word (word) values  ('prude');
insert into black_list_word (word) values  ('pube');
insert into black_list_word (word) values  ('pubic');
insert into black_list_word (word) values  ('pubis');
insert into black_list_word (word) values  ('punkass');
insert into black_list_word (word) values  ('punky');
insert into black_list_word (word) values  ('puss');
insert into black_list_word (word) values  ('pussies');
insert into black_list_word (word) values  ('pussy');
insert into black_list_word (word) values  ('pussypounder');
insert into black_list_word (word) values  ('puto');
insert into black_list_word (word) values  ('queaf');
insert into black_list_word (word) values  ('queef');
insert into black_list_word (word) values  ('queef');
insert into black_list_word (word) values  ('queer');
insert into black_list_word (word) values  ('queero');
insert into black_list_word (word) values  ('queers');
insert into black_list_word (word) values  ('quicky');
insert into black_list_word (word) values  ('quim');
insert into black_list_word (word) values  ('racy');
insert into black_list_word (word) values  ('rape');
insert into black_list_word (word) values  ('raped');
insert into black_list_word (word) values  ('raper');
insert into black_list_word (word) values  ('rapist');
insert into black_list_word (word) values  ('raunch');
insert into black_list_word (word) values  ('rectal');
insert into black_list_word (word) values  ('rectum');
insert into black_list_word (word) values  ('rectus');
insert into black_list_word (word) values  ('reefer');
insert into black_list_word (word) values  ('reetard');
insert into black_list_word (word) values  ('reich');
insert into black_list_word (word) values  ('retard');
insert into black_list_word (word) values  ('retarded');
insert into black_list_word (word) values  ('revue');
insert into black_list_word (word) values  ('rimjob');
insert into black_list_word (word) values  ('ritard');
insert into black_list_word (word) values  ('rtard');
insert into black_list_word (word) values  ('r-tard');
insert into black_list_word (word) values  ('rum');
insert into black_list_word (word) values  ('rump');
insert into black_list_word (word) values  ('rumprammer');
insert into black_list_word (word) values  ('ruski');
insert into black_list_word (word) values  ('s.h.i.t.');
insert into black_list_word (word) values  ('s.o.b.');
insert into black_list_word (word) values  ('s0b');
insert into black_list_word (word) values  ('sadism');
insert into black_list_word (word) values  ('sadist');
insert into black_list_word (word) values  ('scag');
insert into black_list_word (word) values  ('scantily');
insert into black_list_word (word) values  ('schizo');
insert into black_list_word (word) values  ('schlong');
insert into black_list_word (word) values  ('screw');
insert into black_list_word (word) values  ('screwed');
insert into black_list_word (word) values  ('scrog');
insert into black_list_word (word) values  ('scrot');
insert into black_list_word (word) values  ('scrote');
insert into black_list_word (word) values  ('scrotum');
insert into black_list_word (word) values  ('scrud');
insert into black_list_word (word) values  ('scum');
insert into black_list_word (word) values  ('seaman');
insert into black_list_word (word) values  ('seamen');
insert into black_list_word (word) values  ('seduce');
insert into black_list_word (word) values  ('semen');
insert into black_list_word (word) values  ('sex');
insert into black_list_word (word) values  ('sexual');
insert into black_list_word (word) values  ('sh1t');
insert into black_list_word (word) values  ('s-h-1-t');
insert into black_list_word (word) values  ('shamedame');
insert into black_list_word (word) values  ('shit');
insert into black_list_word (word) values  ('s-h-i-t');
insert into black_list_word (word) values  ('shite');
insert into black_list_word (word) values  ('shiteater');
insert into black_list_word (word) values  ('shitface');
insert into black_list_word (word) values  ('shithead');
insert into black_list_word (word) values  ('shithole');
insert into black_list_word (word) values  ('shithouse');
insert into black_list_word (word) values  ('shits');
insert into black_list_word (word) values  ('shitt');
insert into black_list_word (word) values  ('shitted');
insert into black_list_word (word) values  ('shitter');
insert into black_list_word (word) values  ('shitty');
insert into black_list_word (word) values  ('shiz');
insert into black_list_word (word) values  ('sissy');
insert into black_list_word (word) values  ('skag');
insert into black_list_word (word) values  ('skank');
insert into black_list_word (word) values  ('slave');
insert into black_list_word (word) values  ('sleaze');
insert into black_list_word (word) values  ('sleazy');
insert into black_list_word (word) values  ('slut');
insert into black_list_word (word) values  ('slutdumper');
insert into black_list_word (word) values  ('slutkiss');
insert into black_list_word (word) values  ('sluts');
insert into black_list_word (word) values  ('smegma');
insert into black_list_word (word) values  ('smut');
insert into black_list_word (word) values  ('smutty');
insert into black_list_word (word) values  ('snatch');
insert into black_list_word (word) values  ('sniper');
insert into black_list_word (word) values  ('snuff');
insert into black_list_word (word) values  ('s-o-b');
insert into black_list_word (word) values  ('sodom');
insert into black_list_word (word) values  ('souse');
insert into black_list_word (word) values  ('soused');
insert into black_list_word (word) values  ('sperm');
insert into black_list_word (word) values  ('spic');
insert into black_list_word (word) values  ('spick');
insert into black_list_word (word) values  ('spik');
insert into black_list_word (word) values  ('spiks');
insert into black_list_word (word) values  ('spooge');
insert into black_list_word (word) values  ('spunk');
insert into black_list_word (word) values  ('steamy');
insert into black_list_word (word) values  ('stfu');
insert into black_list_word (word) values  ('stiffy');
insert into black_list_word (word) values  ('stoned');
insert into black_list_word (word) values  ('strip');
insert into black_list_word (word) values  ('stroke');
insert into black_list_word (word) values  ('stupid');
insert into black_list_word (word) values  ('suck');
insert into black_list_word (word) values  ('sucked');
insert into black_list_word (word) values  ('sucking');
insert into black_list_word (word) values  ('sumofabiatch');
insert into black_list_word (word) values  ('t1t');
insert into black_list_word (word) values  ('tampon');
insert into black_list_word (word) values  ('tard');
insert into black_list_word (word) values  ('tawdry');
insert into black_list_word (word) values  ('teabagging');
insert into black_list_word (word) values  ('teat');
insert into black_list_word (word) values  ('terd');
insert into black_list_word (word) values  ('teste');
insert into black_list_word (word) values  ('testee');
insert into black_list_word (word) values  ('testes');
insert into black_list_word (word) values  ('testicle');
insert into black_list_word (word) values  ('testis');
insert into black_list_word (word) values  ('thrust');
insert into black_list_word (word) values  ('thug');
insert into black_list_word (word) values  ('tinkle');
insert into black_list_word (word) values  ('tit');
insert into black_list_word (word) values  ('titfuck');
insert into black_list_word (word) values  ('titi');
insert into black_list_word (word) values  ('tits');
insert into black_list_word (word) values  ('tittiefucker');
insert into black_list_word (word) values  ('titties');
insert into black_list_word (word) values  ('titty');
insert into black_list_word (word) values  ('tittyfuck');
insert into black_list_word (word) values  ('tittyfucker');
insert into black_list_word (word) values  ('toke');
insert into black_list_word (word) values  ('toots');
insert into black_list_word (word) values  ('tramp');
insert into black_list_word (word) values  ('transsexual');
insert into black_list_word (word) values  ('trashy');
insert into black_list_word (word) values  ('tubgirl');
insert into black_list_word (word) values  ('turd');
insert into black_list_word (word) values  ('tush');
insert into black_list_word (word) values  ('twat');
insert into black_list_word (word) values  ('twats');
insert into black_list_word (word) values  ('ugly');
insert into black_list_word (word) values  ('undies');
insert into black_list_word (word) values  ('unwed');
insert into black_list_word (word) values  ('urinal');
insert into black_list_word (word) values  ('urine');
insert into black_list_word (word) values  ('uterus');
insert into black_list_word (word) values  ('uzi');
insert into black_list_word (word) values  ('vag');
insert into black_list_word (word) values  ('vagina');
insert into black_list_word (word) values  ('valium');
insert into black_list_word (word) values  ('viagra');
insert into black_list_word (word) values  ('virgin');
insert into black_list_word (word) values  ('vixen');
insert into black_list_word (word) values  ('vodka');
insert into black_list_word (word) values  ('vomit');
insert into black_list_word (word) values  ('voyeur');
insert into black_list_word (word) values  ('vulgar');
insert into black_list_word (word) values  ('vulva');
insert into black_list_word (word) values  ('wad');
insert into black_list_word (word) values  ('wang');
insert into black_list_word (word) values  ('wank');
insert into black_list_word (word) values  ('wanker');
insert into black_list_word (word) values  ('wazoo');
insert into black_list_word (word) values  ('wedgie');
insert into black_list_word (word) values  ('weed');
insert into black_list_word (word) values  ('weenie');
insert into black_list_word (word) values  ('weewee');
insert into black_list_word (word) values  ('weiner');
insert into black_list_word (word) values  ('weirdo');
insert into black_list_word (word) values  ('wench');
insert into black_list_word (word) values  ('wetback');
insert into black_list_word (word) values  ('wh0re');
insert into black_list_word (word) values  ('wh0reface');
insert into black_list_word (word) values  ('whitey');
insert into black_list_word (word) values  ('whiz');
insert into black_list_word (word) values  ('whoralicious');
insert into black_list_word (word) values  ('whore');
insert into black_list_word (word) values  ('whorealicious');
insert into black_list_word (word) values  ('whored');
insert into black_list_word (word) values  ('whoreface');
insert into black_list_word (word) values  ('whorehopper');
insert into black_list_word (word) values  ('whorehouse');
insert into black_list_word (word) values  ('whores');
insert into black_list_word (word) values  ('whoring');
insert into black_list_word (word) values  ('wigger');
insert into black_list_word (word) values  ('womb');
insert into black_list_word (word) values  ('woody');
insert into black_list_word (word) values  ('wop');
insert into black_list_word (word) values  ('wtf');
insert into black_list_word (word) values  ('x-rated');
insert into black_list_word (word) values  ('xxx');
insert into black_list_word (word) values  ('yeasty');
insert into black_list_word (word) values  ('yobbo');
insert into black_list_word (word) values  ('zoophile');



-- status
-- ------------------------------------------------
insert into status (status_description,is_user_status,is_match_table_status ) values  ('Registered',1,0,0);
insert into status (status_description,is_user_status,is_match_table_status ) values  ('Active',1,0,0);
insert into status (status_description,is_user_status,is_match_table_status ) values  ('Suspended',1,0,0);
insert into status (status_description,is_user_status,is_match_table_status ) values  ('Barred',1,0,0);
insert into status (status_description,is_user_status,is_match_table_status ) values  ('Matched',0,1,0);
insert into status (status_description,is_user_status,is_match_table_status ) values  ('Like',0,1,0);
insert into status (status_description,is_user_status,is_match_table_status ) values  ('Maybe',0,1,0);
insert into status (status_description,is_user_status,is_match_table_status ) values  ('Goodbye',0,1,0);
insert into status (status_description,is_user_status,is_match_table_status ) values  ('Message Sent',0,0,1);
insert into status (status_description,is_user_status,is_match_table_status ) values  ('Message Received',0,0,1);
insert into status (status_description,is_user_status,is_match_table_status ) values  ('Responded',0,0,1);

-- user_profile
-- ------------------------------------------------
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Adrian','O''Sullivan','16230124@ul.ie','1990-01-01','1','1','0','','1',1);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','John','Doe','john.doe@gmail.com','2000-01-01','1','1','0','','2',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Gavin','Hunter','Gavin.Hunter@gmail.com','1990-01-01','1','1','0','','3',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Carol','James','Carol.James@gmail.com','1990-01-01','2','2','0','','4',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Yvonne','Edmunds','Yvonne.Edmunds@gmail.com','1990-01-01','2','2','0','','5',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Max','Glover','Max.Glover@gmail.com','1990-01-01','1','1','0','','6',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Dan','King','Dan.King@gmail.com','1990-01-01','1','1','0','','7',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Carolyn','Thomson','Carolyn.Thomson@gmail.com','1990-01-01','2','2','0','','8',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Angela','Martin','Angela.Martin@gmail.com','1990-01-01','2','2','0','','9',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Melanie','Slater','Melanie.Slater@gmail.com','1990-01-01','2','2','0','','10',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Jennifer','Langdon','Jennifer.Langdon@gmail.com','1990-01-01','2','2','0','','11',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Paul','Alsop','Paul.Alsop@gmail.com','1990-01-01','1','1','0','','12',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Owen','Wilkins','Owen.Wilkins@gmail.com','1990-01-01','1','1','0','','13',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Ella','Taylor','Ella.Taylor@gmail.com','1990-01-01','2','2','0','','14',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Amanda','Young','Amanda.Young@gmail.com','1990-01-01','2','2','0','','15',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Abigail','Mackay','Abigail.Mackay@gmail.com','1990-01-01','2','2','0','','16',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Lily','Avery','Lily.Avery@gmail.com','1990-01-01','2','2','0','','17',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Madeleine','Wilson','Madeleine.Wilson@gmail.com','1990-01-01','2','2','0','','18',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Carl','Stewart','Carl.Stewart@gmail.com','1990-01-01','1','1','0','','19',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Faith','James','Faith.James@gmail.com','1990-01-01','2','2','0','','20',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Lisa','Sharp','Lisa.Sharp@gmail.com','1990-01-01','2','2','0','','21',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Lucas','Short','Lucas.Short@gmail.com','1990-01-01','1','1','0','','22',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Una','Nash','Una.Nash@gmail.com','1990-01-01','2','2','0','','23',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Jacob','Newman','Jacob.Newman@gmail.com','1990-01-01','1','1','0','','24',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Dorothy','Mathis','Dorothy.Mathis@gmail.com','1990-01-01','2','2','0','','25',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Irene','Hemmings','Irene.Hemmings@gmail.com','1990-01-01','2','2','0','','26',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Caroline','Davies','Caroline.Davies@gmail.com','1990-01-01','2','2','0','','27',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Phil','Sharp','Phil.Sharp@gmail.com','1990-01-01','1','1','0','','28',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Ella','Hughes','Ella.Hughes@gmail.com','1990-01-01','2','2','0','','29',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Samantha','Ferguson','Samantha.Ferguson@gmail.com','1990-01-01','2','2','0','','30',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Warren','Rutherford','Warren.Rutherford@gmail.com','1990-01-01','1','1','0','','31',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Elizabeth','Lewis','Elizabeth.Lewis@gmail.com','1990-01-01','2','2','0','','32',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Jane','Langdon','Jane.Langdon@gmail.com','1990-01-01','2','2','0','','33',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Ava','Pullman','Ava.Pullman@gmail.com','1990-01-01','2','2','0','','34',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Vanessa','Campbell','Vanessa.Campbell@gmail.com','1990-01-01','2','2','0','','35',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Diane','Henderson','Diane.Henderson@gmail.com','1990-01-01','2','2','0','','36',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Madeleine','Duncan','Madeleine.Duncan@gmail.com','1990-01-01','2','2','0','','37',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Diana','Mackay','Diana.Mackay@gmail.com','1990-01-01','2','2','0','','38',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Una','Rutherford','Una.Rutherford@gmail.com','1990-01-01','2','2','0','','39',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Jessica','Walsh','Jessica.Walsh@gmail.com','1990-01-01','2','2','0','','40',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Ella','Terry','Ella.Terry@gmail.com','1990-01-01','2','2','0','','41',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Robert','Wilkins','Robert.Wilkins@gmail.com','1990-01-01','1','1','0','','42',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Bella','Walsh','Bella.Walsh@gmail.com','1990-01-01','2','2','0','','43',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Penelope','Mackay','Penelope.Mackay@gmail.com','1990-01-01','2','2','0','','44',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Amanda','Hart','Amanda.Hart@gmail.com','1990-01-01','2','2','0','','45',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Virginia','Randall','Virginia.Randall@gmail.com','1990-01-01','2','2','0','','46',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Gabrielle','Edmunds','Gabrielle.Edmunds@gmail.com','1990-01-01','2','2','0','','47',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Jessica','Anderson','Jessica.Anderson@gmail.com','1990-01-01','2','2','0','','48',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Jan','Buckland','Jan.Buckland@gmail.com','1990-01-01','1','1','0','','49',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Stewart','James','Stewart.James@gmail.com','1990-01-01','1','1','0','','50',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Emma','White','Emma.White@gmail.com','1990-01-01','2','2','0','','51',0);
insert into user_profile (password_hash,first_name,sur_name,email,date_of_birth,gender_id,gender_preference_id,black_listed_user,black_listed_reason,user_status_id,is_administrator) values  ('','Lily','Paige','Lily.Paige@gmail.com','1990-01-01','2','2','0','','52',0);


-- user_communication
-- ------------------------------------------------

-- match_table
-- ------------------------------------------------


-- user_interests
-- ------------------------------------------------

commit;
